### ISSUE TITLE
Any photos of the finished project/wiring?

### ISSUE THREAD

**Issue by Djent-** [Cobertos/CSGO-StatTrak-Nerf-Arduino-Mod#1]
-

**Comment by Cobertos** [comment]
Yeah, I'll update the readme when I get home tonight with some pics. It looked really nice, the worst thing was the refresh rate on the OLED I was using + the library.

I might still have the wiring diagrams too

**Comment by Cobertos** [comment]
Alright, tons of new stuff, though I didn't find any wiring diagrams. The best I had was a whiteboard picture of the wiring lol

It's all in the readme (except the whiteboard picture)

**Comment by Djent-** [comment]
Thanks!
